name: amazon_clone
description: "Amazon clone."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  # icons
  cupertino_icons: ^1.0.8

  # network
  http: ^1.2.2

  # state management
  provider: ^6.1.2

  # local file system
  shared_preferences: ^2.3.2

  # carousel images
  carousel_slider: ^5.0.0

  # styling
  dotted_border: ^2.1.0

  # file picker
  file_picker: ^8.1.2

  # remote image database
  cloudinary_public: ^0.23.1

  # rating bar
  flutter_rating_bar: ^4.0.1

  # apple, google pay
  pay: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/applepay.json
    - assets/gpay.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
